# Generated by Django 3.1.5 on 2021-01-10 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('change_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amount',
            name='change',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='amount',
            name='multiplier',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='amount',
            name='total_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
