# Generated by Django 3.1.5 on 2021-01-10 01:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('change_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amount',
            name='change',
        ),
        migrations.AddField(
            model_name='amount',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='amount',
            name='multiplier',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='amount',
            name='total_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
