# Generated by Django 3.1.5 on 2021-01-10 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('change_app', '0002_auto_20210110_0023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amount',
            name='change',
        ),
    ]
